version: '3.8'

services:
  clinique-db:
    image: postgres:14-alpine
    container_name: clinique-db
    environment:
      POSTGRES_DB: clinique_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - clinique_data:/var/lib/postgresql/data
    networks:
      - clinique-net

  clinique-app-server:
    image: quay.io/wildfly/wildfly:26.1.3.Final-jdk17
    container_name: clinique-app-server
    environment:
      - WILDFLY_USER=admin
      - WILDFLY_PASS=admin123
    command: [ "/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0" ]
    ports:
      - "8080:8080"
      - "9990:9990"
    depends_on:
      - clinique-db
    networks:
      - clinique-net

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin@admin.com
    depends_on:
      - clinique-db
    networks:
      - clinique-net

networks:
  clinique-net:
    driver: bridge

volumes:
  clinique_data:
    driver: local